### ISSUE TITLE
Issue with pxcsession.h header file

### ISSUE THREAD

**Issue by shrutim1** [vitomedved/joint-tracking#1]
Hi!
I am working on skeleton tracking using intel realsense R200 camera.
I am unable to find where the "px" header files in CSkeletonTracking.hpp are located and how do I download them. I would appreciate any help on this issue.

**Comment by shrutim1** [comment]
Does this code work on WIndows or on Ubuntu as well?

**Comment by vitomedved** [comment]
Hello shrutim1,
Sorry for late response. Will ad e-mail in readme so people can reach to me faster.

This code is only tested in Windows, but I think it should work for Linux also. If you still need it I can check it just to be sure.

As for the px files, they are saved locally on my computer, I will commit them in joint-tracking / Project2/include/rs. If you googled this problem, you probably already found Intel Realsense SDK where you can get this files yourself and add paths in Visual Studio.
